### Get JWT Bearer Token
POST https://localhost:5001/login
Content-Type: application/json

{
  "username": "admin",
  "password": "pass"
}

> {% client.global.set("auth_token", response.body.token); %}

### Create Card with invalid request
POST https://localhost:5001/cards
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "cardNumber": "less than 15"
}

### Create Card
POST https://localhost:5001/cards
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "cardNumber": "123456789012345"
}

> {% client.global.set("card_id", response.body.id); %}

### Get Card
GET https://localhost:5001/cards/{{card_id}}
Authorization: Bearer {{auth_token}}

### Post Pay with invalid request
POST https://localhost:5001/cards/{{card_id}}/pay
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "amount": -1
}

### Post Pay
POST https://localhost:5001/cards/{{card_id}}/pay
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "amount": 10.0
}

### Get Card with new Balance
GET https://localhost:5001/cards/{{card_id}}
Authorization: Bearer {{auth_token}}